name = "espresso_templatizer"
version = "0.0.1"
description = "A templating library for espresso apps on gleam."

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
repository = { type = "github", user = "espresso-gleam", repo = "espresso_templates" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.29"
nibble = "~> 0.2"
gleam_javascript = "~> 0.4"
glint = "~> 0.12.0-rc5"

[dev-dependencies]
gleeunit = "~> 0.10"
